#!/bin/bash

CHAL="pwn_1";
OUTPORT=10000;
INPORT=10000;

if [[ $# == 0 ]]; then
    echo "========= $CHAL ========="
    echo "Usage:";
    echo "Build challenge:     ./snippet build";
    echo "Rebuild challenge:   ./snippet rebuild";
    echo "Start challenge:     ./snippet start";
    echo "Stop challenge:      ./snippet stop";
    exit 0
fi

DOCKERNAME="taiwan_holy_young_pwn-${CHAL// /_}"

if [[ $1 == "build" ]]; then
    docker build -t $DOCKERNAME .;
elif [[ $1 == "rebuild" ]]; then
    docker rmi $DOCKERNAME;
    docker build -t $DOCKERNAME .;
elif [[ $1 == "start" ]]; then
    docker run -p $OUTPORT:$INPORT --name $DOCKERNAME -d $DOCKERNAME;
elif [[ $1 == "stop" ]]; then
    docker stop $DOCKERNAME;
    docker rm $DOCKERNAME;
fi
